gen_feature_with_jackhmmer: No # if Yes, jackhmmer_result will be used to generate feature

path:
        output_base: /data/work/qing/DeepContact/test

# run hhblits and reformat output to aln file
# see hhblits_runner.py
hhblits:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/hhsuite-2.0.16-linux-x86_64/bin/hhblits
        uniprot_db: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/uniprot20_2016_02/uniprot20_2016_02
        n_threads: 1
        n_iters: 3
        e_value: 0.001
        maxfilt: 500000
        diff: inf
        id: 99
        cov: 50

# run jackhmmer
# see jackhmmer_runner.py
jackhmmer:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/hmmer/binaries/jackhmmer
        uniref_db: /scratch/aminoproject_fluxoe/zcx/uniref90
        n_threads: 1
        inc_E: 10.0
        n_iter: 3

# run hhfilter after jackhmmer
# see jackhmmer_runner.py
hhfilter:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/hhsuite-2.0.16-linux-x86_64/bin/hhfilter

# run ccmpred
# see ccmpred_runner.py
ccmpred:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/bin/ccmpred
        n_threads: 1
        # optional:
        #cuda_dev: 6   # (do not include if use default cuda device)

# run freecontact in evfold mode
# see freecontact_runner.py
freecontact:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/bin/freecontact
        n_threads: 1

# run alnstats
# see alnstats_runner.py
alnstats:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/metapsicov/bin/alnstats
        n_processes: 1

# run blastpgp
# see ss_runner.py
blast:
        command: /nfs/amino-library/blast/bin/blastpgp
        n_processes: 1
        n_threads: 1
        n_iters: 3
        e_value: 0.001
        database: /nfs/amino-library/uniref90/uniref90.fasta

# run makemat
# see ss_runner.py
makemat:
        command: /nfs/amino-library/blast/bin/makemat
        n_processes: 1
        
# run psipred
# see ss_runner.py
psipred:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/psipred/bin/psipred
        data: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/psipred/data
        n_processes: 1

# run psipred_pass2
# see ss_runner.py
psipred_pass2:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/psipred/bin/psipass2
        n_processes: 1
        n_iters: 1
        DCA: 1.0
        DCB: 1.0

# run solvpred
# see ss_runner.py
solvpred:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/metapsicov/bin/solvpred
        data: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/metapsicov/data/weights_solv.dat
        n_processes: 1

# run hhmake (includes neff)
# see hhmake_runner
hhmake:
        command: /nfs/amino-home/zcx/Projects/EVfold/ext/deepcontact/hhsuite-2.0.16-linux-x86_64/bin/hhmake
        n_processes: 1
